[package]
name = "hovo_core"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
regex = "1.11.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
